version: '2.4'
services:
  adminpanel:
    build: .
    ports:
      - 8888:5000
    read_only: true
    privileged: true
    cap_drop:
      - all
    cap_add:
      - chown
      - setuid
      - setgid
      - sys_admin
      - mknod
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
